---

- name: Add the Jenkins repo APT Key
  become: true
  apt_key:
    url: "https://pkg.jenkins.io/debian-stable/jenkins.io.key"
    state: present

- name: Add the Jenkins package repository
  become: true
  apt_repository:
    repo: "deb https://pkg.jenkins.io/debian-stable binary/"
    state: present

# To force a particular version:  "{{ package_name }}=2.138.3.1"
- name: Install Jenkins
  become: true
  apt:
    update_cache: yes
    name: "jenkins"