---

- name: create directory to store the CfgMgt stuff on the local user
  file:
    path: "{{ jenkins_cfgmgt_dir }}"
    state: directory
    owner: "ubuntu"
    group: "ubuntu"
    mode: u=rwx,g=,o=


# As we are using SSO, retrieve the CFG_Mgt API token from the CJOC and enable it locally
- name: Capture the CFG_mgt API token from CJOC
  become: true
  ansible.builtin.command: "cat /var/lib/cloudbees-core-oc/secrets/defaultCfgToken"
  delegate_to: "cjoc"
  register: APItoken


- name: create auth file locally with what we captured
  copy:
    dest: "{{ jenkins_cfgmgt_dir }}/cfgAuthfile"
    content: "{{ APItoken.stdout }}"
    force: yes
    backup: yes
    owner: "ubuntu"
    group: "ubuntu"
    mode: u=rw,g=,o=


- name: copy jenkins-cli.jar to cfgMgt directory
  get_url:
    url: "{{ cm_url }}/jnlpJars/jenkins-cli.jar"
    dest: "{{ jenkins_cfgmgt_dir }}/jenkins-cli.jar"
    timeout: 120
  register: result
  until: result.failed == false
  retries: 20
  delay: 10

# - name: Output of Script execution
#   debug: 
#     var: result

- name: Create a CLI command varialble on remote (for debug purposes)
  template:
    src: "remote_CLI_config.j2"
    dest: "{{ jenkins_cfgmgt_dir }}/load_CLI_command.sh"
    force: yes
    mode: u=rwx,g=rx,o=rx

- name: Copy a README to explain how to use the CLI command
  copy:
    src: "remote-CLI-readme.txt"
    dest: "{{ jenkins_cfgmgt_dir }}/CLI_README.txt"
    force: yes
    mode: u=rwx,g=rx,o=rx    


- name: "create \"{{ jenkins_cfgmgt_script_dir }}\" to store the script executed by these scripts"
  file:
    path: "{{ jenkins_cfgmgt_script_dir }}"
    state: directory
    mode: u=rwx,g=rx,o=rx

