

- hosts: all
  roles:
    - common

- hosts: docker_agent
  vars:
    jenkins_node_type: "agent_docker"
  roles:
    - agent_docker
    - docker_ldap

- hosts: cjoc 
  roles:
    - java8_jdk
    - cjoc
    - ldap_tester

- hosts: cm1 
  roles:
    - java8_jdk
    - client_master
    - ldap_tester    

- hosts: agent_1 
  roles:
    - java8_jdk
    - agent_jnlp
