

- hosts: all
  roles:
    - common

- hosts: docker_agent
  vars:
    jenkins_node_type: "agent_docker"
  roles:
    - agent_docker
    - docker_ldap

- hosts: cjoc 
  roles:
    - java8_jdk
    - cjoc
    - ldap_tester

- hosts: cm1 
  roles:
    - java8_jdk
    - client_master
    - ldap_tester    


# - hosts: jmm_client_master

#   # this is required as only python3 is installed on Ubuntu AMI (Ansible fails otherwise)
#   gather_facts: False

#   vars:
#     jenkins_node_type: "master"
#     ansible_python_interpreter: auto

#   roles:
#     - general
#     - jenkins  


# - hosts: jmm_agent1

#   # this is required as only python3 is installed on Ubuntu AMI (Ansible fails otherwise)
  
#   gather_facts: False

#   vars:
#     jenkins_node_type: "agent_jnlp"
#     ansible_python_interpreter: auto

#   roles:
#     - agent_jnlp
