

- hosts: cm1 
  roles:
    - java8_jdk
    - client_master
    - ldap_tester


# - hosts: jmm_agent1

#   # this is required as only python3 is installed on Ubuntu AMI (Ansible fails otherwise)
  
#   gather_facts: False

#   vars:
#     jenkins_node_type: "agent_jnlp"
#     ansible_python_interpreter: auto

#   roles:
#     - agent_jnlp
