- hosts: all
  gather_facts: no
  tasks:
    # try pinging the system now
    - name: Trying if the Ansible communication works now (using a Ping)
      ansible.builtin.ping:

    - name: Update the system
      become: true
      apt:
        update-cache: yes
        upgrade: "yes"

    # Used to validate that it is possible to install a package and that everything is working fine
    - name: Install COWSAY
      become: true
      apt: 
        update_cache: yes
        name: cowsay

    - name: "the cow say hello"
      ansible.builtin.command: cowsay hello, world!
      register: cowsay_out
    - debug: var=cowsay_out.stdout_lines

    - name: Install OpenJdk 8 (JRE)
      become: true
      apt:
        update_cache: yes
        name: openjdk-8-jre

    - name: Install JQ (Json Query tool)
      become: true
      apt:
        update_cache: yes
        name: jq

    - name: set VIMs background to dark by default
      lineinfile:
        path: "/home/ubuntu/.vimrc"
        create: yes
        owner: "ubuntu"
        group: "ubuntu"
        mode: u=rw,g=r,o=r
        insertafter: EOF
        line: ':set background=dark'
