option_friendly_name: "Cloudbees Core Operation Center"
key_url: "https://downloads.cloudbees.com/cloudbees-core/traditional/operations-center/rolling/debian/cloudbees.com.key"
repo_url: "deb https://downloads.cloudbees.com/cloudbees-core/traditional/operations-center/rolling/debian binary/"
package_name: "cloudbees-core-oc"
used_port: "8888"
jenkins_user: "{{ package_name }}"
jenkins_home_dir: "/var/lib/{{ package_name }}"
jenkins_cfgmgt_dir: "/home/ubuntu/ConfigMgt"
jenkins_cfgmgt_script_dir: "{{ jenkins_cfgmgt_dir }}/jenkins_scripts"
cjoc_url: "http://cjoc.the-captains-shack.com"
jenkins_cfgmgt_user: "Jenkins_cfg"
CLI_command: java -jar {{ jenkins_cfgmgt_dir }}/jenkins-cli.jar -s {{ cjoc_url }} -auth @{{ jenkins_cfgmgt_dir }}/cfgAuthfile

default_plugins:
  - cloudbees-ssh-slaves
  - cloudbees-ha
  - cloudbees-update-center-plugin
  - nectar-rbac
  - ssh-credentials
  - ldap
  - operations-center-jnlp-controller
  - cloudbees-support
  - operations-center-updatecenter
  - operations-center-rbac
  - credentials-binding
  - infradna-backup
  - cloudbees-monitoring
  - operations-center-sso
  - script-security
  - cloudbees-folders-plus
  - operations-center-clusterops
  - mailer
  - antisamy-markup-formatter
  - cloudbees-jenkins-advisor
  - operations-center-monitoring
  