---

- name: create directory to store the CfgMgt stuff on the local user
  file:
    path: "{{ jenkins_cfgmgt_dir }}"
    state: directory
    owner: "ubuntu"
    group: "ubuntu"
    mode: u=rwx,g=,o=

# retrieve the token
- name: copy the configuration management token to the current user
  become: true
  copy:
    remote_src: true
    src: "/var/lib/{{ jenkins_user }}/secrets/defaultCfgToken"
    dest: "{{ jenkins_cfgmgt_dir }}/cfgAuthfile"
    force: yes
    backup: no
    owner: "ubuntu"
    group: "ubuntu"
    mode: u=rw,g=,o= 

- name: copy jenkins-cli.jar to cfgMgt directory
  get_url:
    url: "{{ jenkins_url }}/jnlpJars/jenkins-cli.jar"
    dest: "{{ jenkins_cfgmgt_dir }}/jenkins-cli.jar"
    timeout: 120
  ignore_errors: yes  

- name: Create a CLI command varialble on remote (for debug purposes)
  template:
    src: "remote_CLI_config.j2"
    dest: "{{ jenkins_cfgmgt_dir }}/load_CLI_command.sh"
    force: yes
    mode: u=rwx,g=rx,o=rx

- name: Copy a README to explain how to use the CLI command
  copy:
    src: "remote-CLI-readme.txt"
    dest: "{{ jenkins_cfgmgt_dir }}/CLI_README.txt"
    force: yes
    mode: u=rwx,g=rx,o=rx    
