---

- name: copy security setup groovy script 
  copy:
    src: "setCJOCsecurity.groovy"
    dest: "{{ jenkins_cfgmgt_script_dir }}/setCJOCsecurity.groovy"
    force: yes
    mode: u=rw,g=r,o=r

- name: Execute security setup script
  ansible.builtin.shell: "cat {{ jenkins_cfgmgt_script_dir }}/setCJOCsecurity.groovy | {{ CLI_command }} groovy ="
