---

- name: create the jenkins user
  become: true
  user:
    name: jenkins
    shell: /bin/bash

- name: download the agent.jar from the client master
  become: true
  get_url:
    url: "http://cm1.the-captains-shack.com/jnlpJars/agent.jar"
    dest: "/home/jenkins/agent.jar"
    mode: "u=xrw,g=xr,o=xr"
    owner: "jenkins"
    group: "jenkins"

- name: Capture the startup file we prapared on the Client Master
  ansible.builtin.command: "cat /home/ubuntu/ConfigMgt/jenkins_scripts/start_jnlp_agent.sh"
  delegate_to: "cm1"
  register: jnlp_start_script_text

- name: create file locally with what we captured
  shell: "echo '{{ jnlp_start_script_text.stdout }}' >/home/ubuntu/start_jnlp_agent.sh"
  args: 
    creates: /home/ubuntu/start_jnlp_agent.sh

- name: copy temporary startup file to definitive location
  become: true
  copy:
    src: "/home/ubuntu/start_jnlp_agent.sh"
    dest: "/home/jenkins/start_jnlp_agent.sh"
    remote_src: yes
    owner: "jenkins"
    group: "jenkins"
    mode: "u=xrw,g=xr,o=xr"

- name: create the directory to store the JNLP Agent log file
  become: true
  file:
    path: "/home/jenkins/logs"
    state: directory
    owner: "jenkins"
    group: "jenkins"
    mode: "u=xrw,g=xr,o=xr"

# We should only execute if it is not running yet. But I didn't find a way to execute a "ps aux | grep ..." or pgrep. But there is no harm: the second start just fails.
- name: Start the JNLP agent
  become: yes
  become_user: jenkins
  ansible.builtin.shell: "cd /home/jenkins; nohup /home/jenkins/start_jnlp_agent.sh >>/home/jenkins/logs/jnlpAgent_stdout.log 2>>/home/jenkins/logs/jnlpAgent_stderr.log &"

# https://stackoverflow.com/questions/25505146/how-to-copy-files-between-two-nodes-using-ansible
# https://stackoverflow.com/questions/23761479/how-can-i-check-via-a-script-or-a-plugin-in-jenkins-whether-a-slave-is-online-be

# https://wiki.jenkins.io/display/JENKINS/Distributed+builds
# http://minimum-viable-automation.com/ansible/use-ansible-create-user-accounts-setup-ssh-keys/
# https://gist.github.com/fulv/3928d098e8c35af1cc5363a4d2d4fcd0
# https://docs.ansible.com/ansible/latest/modules/user_module.html
# `java -jar agent.jar -jnlpUrl http://ec2-100-24-209-228.compute-1.amazonaws.com/computer/Agent-1/slave-agent.jnlp -secret a3247f21578694502a55f92ec9024cd209103dd0ba291e858f5b85c96b4f8966 -workDir "/jenkins-agent-1/"`
# https://jenkins-le-guide-complet.github.io/html/sect-master-slave-strategies.html
# http://objis.com/installation-agent-jenkins/
# https://support.cloudbees.com/hc/en-us/articles/115003929412?q=agent%20jnlp
# https://support.cloudbees.com/hc/en-us/articles/207849467?q=agent%20jnlp
